name:                Day18
version:             0.1.0.0
github:              "haetze/AdventOfCode2020"
license:             GPL-3
author:              "Richard Stewing"
maintainer:          "richy.sting@gmail.com"
copyright:           "2020 Richard Stewing"

extra-source-files: []

description:         Advent Of Code 2020

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.14.0

library:
  source-dirs: src

executables:
  Day18-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day18

tests:
  Day18-test:
    main:                Spec.hs
    source-dirs:         []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day18
